apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: taskschedulerh2
  name: taskschedulerh2
  namespace: default
spec:
  replicas: 3
  minReadySeconds: 45
  selector:
    matchLabels:
      app: taskschedulerh2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: taskschedulerh2
    spec:
      containers:
      - image: adithilokhande/taskschedulerh2:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        name: taskschedulerh2
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: taskschedulerh2
  name: taskschedulerh2
  namespace: default
spec:
  ports:
    - nodePort: 30607
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: taskschedulerh2
  sessionAffinity: ClientIP
  type: LoadBalancer