apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: taskschedulermysql
  name: taskschedulermysql
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      io.kompose.service: taskschedulermysql
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: taskschedulermysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: taskschedulermysql-configmap
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              key: MYSQL_HOST
              name: taskschedulermysql-configmap
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: taskschedulermysql-secret
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PORT
              name: taskschedulermysql-configmap
        - name: MYSQL_USERNAME
          valueFrom:
            configMapKeyRef:
              key: MYSQL_USERNAME
              name: taskschedulermysql-configmap
        image: adithilokhande/taskschedulermysql:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        name: taskschedulermysql
        ports:
        - containerPort: 8080
      restartPolicy: Always
      serviceAccountName: ""
