apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: taskschedulermysql
  name: taskschedulermysql
spec:
  type: LoadBalancer
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: taskschedulermysql
  sessionAffinity: ClientIP
